#!/bin/bash

####################################
# INIT
####################################

# 設定ファイルの読み込み
. `dirname $0`/.env

dir_name=$DEV_DIRECTORY
input_char="X"
input_name=""
index_num="" # インデックス取得


####################################
# FUNCTIONS
####################################

function open_dev_directory () {
  echo "[Info] Please choose directory..."
  # 配列の中身を全て取り出すには ${HOGE[@]}
  select VAR in ${DEV_DIRECTORY[@]}
  do
    dir_name=$VAR
    break
  done
}

function pick_candidate_projects () {
  echo "Open ${dir_name} ..."
  projects=()
  for path in $dir_name/*; do
    if [ -d $path ]; then # if diretory
      project_name=$(basename $path)
      if [ -z "$1" ] || [[ $project_name == "$1"* ]]; then #$1は引数, -z はnull判定
        projects+=("$project_name")
      fi
    fi
  done

  i=0
  for project in ${projects[@]}; do
    # index_num と一致したら色変更
    if [[ "$index_num" = "$i" ]]; then
      printf "\e[31m%s\e[m\n" "${i}) ${project}"
    elif [ ! $index_num = "" ] && [[ $i = "$index_num"* ]]; then
      printf "\e[33m%s\e[m\n" "${i}) ${project}"
    else
      printf "%s\n" "${i}) ${project}"
    fi
    let i++
  done | column -t

}


##################################
# コードの本体
##################################

if [ $# -ge 1 ]; then
  case "$1" in
    "-d" | "--directory")
      open_dev_directory
      ;;
    "-w" | "where") echo `dirname $0`;;
  esac
fi

clear
pick_candidate_projects

while [ ! "$input_char" = "" ]
do
  echo "IndexNum: ${index_num}"
  read -n 1 -p "Project Name: ${input_name}${pick_candidate_projects}" -s input_char
  echo

  # 矢印入力対策
  if [[ $input_char == $'\x1b' ]]; then
    read -r -n 2 -s rest
    $input_char+="$rest"
    echo $input_char
  fi

  case $input_char in
    "") # enter
      $CODE_EDITOR $dir_name/${projects[index_num]}
      break
      ;;
    $'\x7f\x0a') 
      echo "親";; # backspace hexdump で調べる
    [0-9])
      index_num+="${input_char}"
      clear
      pick_candidate_projects $input_name
      ;;
    *) 
      input_name+="${input_char}"
      clear
      pick_candidate_projects $input_name
  esac
done











