#!/bin/bash

####################################
# INIT
####################################


echo "hello"


# 設定ファイルの読み込み
. `dirname $0`/.env

# DEV_DIRECTORY="~/dev"
# CODE_EDITOR="pstorm"


####################################
# FUNCTIONS
####################################

function open_dev_directory () {
  echo "[Info] Please choose the directory..."
  # 配列の中身を全て取り出すには ${HOGE[@]}
  DIR_NAME=($(ls $DEV_DIRECTORY))
  select VAR in ${DIR_NAME[@]}
  do
    echo $VAR
    echo "Wait to open $DEV_DIRECTORY/$VAR in Code Editor."
    echo "$CODE_EDITOR $DEV_DIRECTORY/$VAR"
    $CODE_EDITOR $DEV_DIRECTORY/$VAR
    break
  done
}

function pick_candidate_projects () {
  projects=()
  for path in $DEV_DIRECTORY/*; do
    if [ -d $path ]; then # if diretory
      project_name=$(basename $path)
      if [ -z "$1" ] || [[ $project_name == "$1"* ]]; then #$1は引数, -z はnull判定
        projects+=("$project_name")
      fi
    fi
  done

  # echo ${projects[@]/%/$'\n'} | column

  i=0
  for project in ${projects[@]}; do
    # index_num と一致したら色変更
    if [[ "$index_num" = "$i" ]]; then
      printf "\e[31m%s\e[m\n" "${i}) ${project}"
    elif [ ! $index_num = "" ] && [[ $i = "$index_num"* ]]; then
      printf "\e[33m%s\e[m\n" "${i}) ${project}"
    else
      printf "%s\n" "${i}) ${project}"
    fi
    let i++
  done | column -t
}


##################################
# コードの本体
##################################

# if [ $# -ge 1 ]; then
#   case "$1" in
#     "open" | "o") open_dev_directory ;;
#     "exec" | "e") exec_project ;;
#     "stop" | "s") stop_project ;;
#     "where" | "w") echo `dirname $0`;;
#   esac
# else
#   echo -e "[Warning]Please set command\npgln open"
# fi


clear
pick_candidate_projects

input_char="X"
input_name=""
index_num="" # インデックス取得

while [ ! "$input_char" = "" ]
do
  echo "IndexNum: ${index_num}"
  read -n 1 -p "Project Name: ${input_name}${pick_candidate_projects}" -s input_char
  echo

  # 矢印入力対策
  if [[ $input_char == $'\x1b' ]]; then
    read -r -n 2 -s rest
    $input_char+="$rest"
    echo $input_char
  fi

  case $input_char in
    "") # enter
      $CODE_EDITOR $DEV_DIRECTORY/${projects[index_num]}
      break ;;
    $'\x7f\x0a') 
      echo "親";; # backspace hexdump で調べる
    [0-9])
      index_num+="${input_char}"
      clear
      pick_candidate_projects $input_name
      ;;
    *) 
      input_name+="${input_char}"
      clear
      pick_candidate_projects $input_name
  esac
done











